baseURL = "https://vorn.ir"
title = "VORN"
theme = "hugo-coder"
#languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Vanguards of Rationalist Networks"
description = "Vanguards of Rationalist Networks, Ltd."
keywords = "company,engineering,systems"
info = ["System Design Firm"]
avatarURL = "images/logo.png"
footerContent = "Knowledge is power."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2019
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 0
enableTwemoji = false
customCSS = []
customSCSS = []
customJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

#[[params.social]]
#name = "LinkedIn"
#icon = "fa fa-linkedin"
#weight = 4
#url = "https://www.linkedin.com/in/johndoe/"

[languages.en]
languageName = ":uk:"
contentDir = "content/en"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

#[[languages.en.menu.main]]
#name = "Projects"
#weight = 3
#url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[languages.fa]
languageName = "پارسی"
title = "پیشگامان شبکه‌های خردگرا"
contentDir = "content/fa"

[languages.fa.params]
author = "پیشگامان شبکه‌های خردگرا"
info = "شرکت مهندسی سیستم"
description = "پایگاه شرکت پیشگامان شبکه‌های خردگرا"
keywords = "مهندسی سیستم"
footerContent = "خرد افسر شهریاران بود&nbsp;&nbsp;&nbsp;&nbsp;همان زیور نامداران بود"
rtl = true
customCSS = ["css/custom.css"]
hideFooter = false
hideCredits = true
hideCopyright = true

[[languages.fa.menu.main]]
name = "درباره"
weight = 1
url = "about/"

[[languages.fa.menu.main]]
name = "نوشته‌ها"
weight = 2
url = "posts/"

#[[languages.fa.menu.main]]
#name = "پروژه‌ها"
#weight = 3
#url = "projects/"

[[languages.fa.menu.main]]
name = "تماس"
weight = 5
url = "contact/"
